### ISSUE TITLE
Login Credentials

### ISSUE THREAD

**Issue by milanbhuva** [voximplant/android-sdk-demo#1]
When i run this application in android device , Application ask for the login credentials i have tried my voximplant account credentials but it's not working

**Comment by YuliaGrigorieva** [comment]
Hello!

To make audio/video calls you need to create Voximplant application, users and rules.
Please take a look at this tutorial especially to "_Creating VoxImplant Application, App Users, App Rule, and VoxEngine Scenario_" part.
https://voximplant.com/blog/voximplant-p2p-video-chat
https://voximplant.com/docs/quickstart/10/understanding-users-applications-and-rules

After you setup application, users and rules, you should be able to login to demo application with voximplant user you have created.

Best regards,
Yulia Grigorieva

**Comment by milanbhuva** [comment]
Hey @YuliaGrigorieva  the suggestion given by you is working good but when i call to the TestUser2 from TestUser1 application shows the error Call is Failed due to Temporarily Unavailable although i open the application in my laptop. 
so please guide me further
Thanks in advance....

**Comment by YuliaGrigorieva** [comment]
Hello!

This error means that the user is not logged in (TestUser2) in general cases.
If you have not set up push notifications, you should have both users TestUser1 and TestUser2 be logged in into demo application (or other demo app on different platform).

Best regards,
Yulia Grigorieva

**Comment by milanbhuva** [comment]
Hello i have installed this app on  other device and login from another
user and it works good but the call is disconnected after 5 to 10 second.
please help

**Comment by YuliaGrigorieva** [comment]
Hello!

It is hard to tell what went wrong.
Please collect logcat traces from both devices (you can filter them by VOXSDK tag in Android Studio) and send them to support@voximplant.com for further detailed investigation.

Best regards,
Yulia Grigorieva
