### ISSUE TITLE
How can I use voximplant sdk and original webrtc sdk?

### ISSUE THREAD

**Issue by DarthMech** [voximplant/android-sdk-demo#3]
Hello.

I try to use voximplant sdk and original webrtc sdk, but when i try build project, i have exception:
```
Execution failed for task ':app:checkDevDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class org.webrtc.AudioProcessingFactory found in modules classes.jar (org.webrtc:google-webrtc:1.0.28032) and webrtc.jar (com.voximplant:voximplant-sdk:2.11.2)
  Duplicate class org.webrtc.AudioSource found in modules classes.jar (org.webrtc:google-webrtc:1.0.28032) and webrtc.jar (com.voximplant:voximplant-sdk:2.11.2)
...
```

Can you help me, how i can use both sdk?

**Comment by YuliaGrigorieva** [comment]
Hello!

Voximplant Android SDK already contains webrtc. Webrtc API are open and can be used directly. 
However we strongly do not recommend to use webrtc and Voximplant Android SDK at the same time as it can break the functionality of both SDKs.

Please provide more details about your case and what would you like to do with webrtc API.

Best regards,
Yulia Grigorieva

**Comment by DarthMech** [comment]
Some classes from google-webrtc that we used in our application, are not exist in Voximplant Android SDK.
So we can not change dependency from google-webrtc to Voximplant Android SDK.
But we want to use both solutions audio/video.

**Comment by YuliaGrigorieva** [comment]
Voximplant Android SDK contains full webrtc api, i.e. we do not strip any interfaces.
However the issue might be related to different versions of webrtc inside Voximplant Android SDK and the one you use from google.

You can contact us at support@voximplant.com and provide more details about required webrtc api and the use cases.
