### ISSUE TITLE
How to handle the calls when device is locked.

### ISSUE THREAD

**Issue by sdtaheri** [voximplant/android-sdk-demo#5]
I exactly followed this demo for implementing calls on Android. There is a quite big issue which I don't have any solutions for and would be happy if you could help me.

• When a Firebase notification arrives, the app tries to open an Activity. Unfortunately, opening activities when the app is not in the foreground is prohibited in recent versions of Android.

[Official documentations](https://developer.android.com/guide/components/activities/background-starts) suggests using one of a few services. 

Does VoxImplant have plans to integrate this into the SDK? This is one of the most needed features for an app which uses VoxImplant SDK. 
How can we notify the user of a call if the app can't be shown?

**Comment by YuliaGrigorieva** [comment]
Hello @sdtaheri !

Thank you for reaching out to us!

We advise to use fullscreen notifications that are available on the latest android versions.
We have implemented them in another demo project "AudioCall" that can be found [here](https://github.com/voximplant/android-demos/tree/master/audiocall). Please take a look at the source code and test on your devices.

[Fullscreen notifications](https://developer.android.com/training/notify-user/time-sensitive) provide the way to show incoming call notification on all screen if the device is locked. This solution looks similar as bringing activity from the background on previous versions.

We do not plan to add any notification services to the Voximplant Android SDK as the way how the application notifies the user about new incoming call differs from the application requirements and design. 

Please let us know if you face any issues.

Best regards,
Yulia Grigorieva

**Comment by sdtaheri** [comment]
Hey @YuliaGrigorieva ,

I tried implementing VoxImplant consulting the demo project you provided. 

In Firebase service file, I [see](https://github.com/voximplant/android-demos/blob/d32c0336fbba4b820e3041e8995dbef7c385a72d/audiocall/src/main/java/com/voximplant/demos/audiocall/push/VoxFirebaseMessagingService.java#L23
) that one would pass the notification content to the VoxClientManager. What I get in my app is that no notifications are shown when the app has been killed previously. I should manually present a full screen notification at this line of code. I mean the `onIncomingCall` method would not get called when the app had been killed and a new notification comes.

In this context, how can I answer the call? The only thing I receive in the notification payload is some info about the Call, e.g. callId, sessionId, etc. How can I construct a new concrete instance of an ICall and answer the call?

Am I in the right direction or am I doing anything wrong?

Thanks in advance.
