### ISSUE TITLE
onRemoteVideoStreamRemoved is not triggered

### ISSUE THREAD

**Issue by MiSikora** [voximplant/android-sdk-demo#6]
`IEndpointListener` has a callback method `onRemoteVideoStreamRemoved()`. However, when I use `sendVideo(false, ICallCompletionHandler)` on an `ICall`, the video stream is not removed and just freezes for the recipient because presumably bytes are no longer transmitted. Is there some specific method that should be called in order to trigger `onRemoteVideoStreamRemoved()`?

I'm using the latest version `2.17.0`.

**Comment by YuliaGrigorieva** [comment]
Hello @MiSikora !

It seems that you did everything right.
Can you please provide more details about your case:
1. do you make a call between android - android, or the endpoint is another client?
2. what is your VoxEngine scenario?

Best regards,
Yulia Grigorieva

**Comment by MiSikora** [comment]
Hi @YuliaGrigorieva 

1. Yes the call is made between two Android devices. At least I'm testing it like this. But in general calls to iOS will be also viable.
2. I'm not really sure what you mean. I initialize `IClient` via `Voximplant.getClientInstance()` with default `ClientConfig`. Then I observe `ICall` for local streams and `IEndpoint` for remote streams, but `onRemoteVideoStreamRemoved()` is never triggered for the recipient. `sendVideo(false)` removes only local stream for me.

**Comment by YuliaGrigorieva** [comment]
Hi @MiSikora !

As a VoxEngine scenario, I meant your JS scenario that is added to your Voximplant applicaition in the Voximplant Control Panel (https://manage.voximplant.com)

It is described here: https://voximplant.com/docs/references/articles/quickstart/apps-scenarios-rules-and-users in the "JavaScript cloud scenarios" part.

Please share your scenario.

Best regards,
Yulia Grigorieva

**Comment by MiSikora** [comment]
```javascript
VoxEngine.forwardCallToUserDirect();
```

That's the whole scenario unless I'm missing something.

**Comment by YuliaGrigorieva** [comment]
Thanks.

And the issue is reproducible with this demo app?

Best regards,
Yulia Grigorieva

**Comment by MiSikora** [comment]
I'm not sure about that. Let me check and get back to you.

**Comment by MiSikora** [comment]
@YuliaGrigorieva 

Thank you very much for your suggestion. It led me to the conclusion that something was wrong in my code. I had a race condition while observing remote streams as attached listeners were not synchronized.

I'll close this one. However, I would have one suggestion. If possible, it would be great to have `addEndpointListener()` and `removeEndpointListener()` on the `IEndpoint` interface so it can dispatch information to all of the listeners instead of just one. Unfortunately, this would be a breaking change, as `setEndpointListener(null)` would not fit this API.

Thanks again for the help.
