### ISSUE TITLE
Sending extra data from caller to receiver

### ISSUE THREAD

**Issue by EssamOmar1994** [voximplant/android-sdk-demo#8]
Hello,

I'm using the android SDK demo and i need to send extra data or headers form the caller and i want the receiver to access this data is there a way to do this in the SDK ?
I have tried the callsettings extra hearders but the receiver doesn't get the data.

Thanks in advance.

**Comment by aylarov** [comment]
Hi, you need to have VoxEngine scenario that supports this by receiving headers from one call and passing them to another call
